import { useState } from 'react'
import { QuillEditorSimple } from '../../../components/ui/QuillEditorSimple'
import { Card } from '../../../components/ui/Card'
import { Button } from '../../../components/ui/Button'

export function QuillDebugPage() {
  const [content, setContent] = useState('')
  
  const sampleBulletList = () => {
    setContent(`
      <h2>Test Content</h2>
      <p>This is a paragraph.</p>
      <ul>
        <li>First bullet point</li>
        <li>Second bullet point</li>
        <li>Third bullet point</li>
      </ul>
      <ol>
        <li>First numbered item</li>
        <li>Second numbered item</li>
      </ol>
    `)
  }

  return (
    <div className="container mx-auto py-8 px-4">
      <h1 className="text-3xl font-bold mb-8">Quill HTML Debug Tool</h1>
      
      <div className="mb-4 space-x-2">
        <Button onClick={sampleBulletList}>Load Sample Content</Button>
        <Button onClick={() => setContent('')} variant="outline">Clear</Button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Editor */}
        <Card className="p-4">
          <h2 className="text-lg font-semibold mb-2">1. Create content in editor:</h2>
          <QuillEditorSimple
            content={content}
            onChange={(newContent) => {
              console.log('Content changed:', newContent)
              setContent(newContent)
            }}
            height="300px"
            enableDebugLogs={false}
          />
        </Card>

        {/* Raw HTML Output */}
        <Card className="p-4">
          <h2 className="text-lg font-semibold mb-2">2. Raw HTML generated by Quill:</h2>
          <div className="bg-gray-900 text-green-400 p-4 rounded font-mono text-xs overflow-auto max-h-[300px]">
            <pre>{content || '(empty)'}</pre>
          </div>
        </Card>
      </div>

      {/* Rendered without any custom styles */}
      <Card className="p-4 mt-4">
        <h2 className="text-lg font-semibold mb-2">3. Raw browser rendering (no Quill styles):</h2>
        <div 
          className="border p-4 rounded"
          dangerouslySetInnerHTML={{ __html: content }}
        />
      </Card>

      {/* Rendered with ql-editor class */}
      <Card className="p-4 mt-4">
        <h2 className="text-lg font-semibold mb-2">4. With ql-editor class (Quill styles):</h2>
        <div 
          className="ql-editor border p-4 rounded"
          dangerouslySetInnerHTML={{ __html: content }}
        />
      </Card>

      {/* Rendered with fixed styles */}
      <Card className="p-4 mt-4">
        <h2 className="text-lg font-semibold mb-2">5. With fixed styles:</h2>
        <div 
          className="quill-display-content border p-4 rounded"
          dangerouslySetInnerHTML={{ __html: content }}
        />
      </Card>

      <style>{`
        /* Fixed styles for display */
        .quill-display-content {
          font-size: 16px;
          line-height: 1.6;
          color: #333;
        }
        
        .quill-display-content h1 { 
          font-size: 2em; 
          margin: 0.5em 0; 
          font-weight: bold; 
        }
        
        .quill-display-content h2 { 
          font-size: 1.5em; 
          margin: 0.5em 0; 
          font-weight: bold; 
        }
        
        .quill-display-content h3 { 
          font-size: 1.17em; 
          margin: 0.5em 0; 
          font-weight: bold; 
        }
        
        .quill-display-content p { 
          margin: 0.5em 0; 
        }
        
        /* Force bullet lists to show bullets */
        .quill-display-content ul {
          list-style: disc !important;
          list-style-type: disc !important;
          margin: 0.5em 0 !important;
          padding-left: 1.5em !important;
        }
        
        .quill-display-content ul li {
          display: list-item !important;
          list-style: disc !important;
          list-style-type: disc !important;
          margin: 0.25em 0 !important;
        }
        
        .quill-display-content ul li::before {
          content: none !important;
        }
        
        /* Force numbered lists */
        .quill-display-content ol {
          list-style: decimal !important;
          list-style-type: decimal !important;
          margin: 0.5em 0 !important;
          padding-left: 1.5em !important;
        }
        
        .quill-display-content ol li {
          display: list-item !important;
          list-style: decimal !important;
          list-style-type: decimal !important;
          margin: 0.25em 0 !important;
        }
        
        .quill-display-content ol li::before {
          content: none !important;
        }
        
        /* Nested lists */
        .quill-display-content ul ul {
          list-style-type: circle !important;
        }
        
        .quill-display-content ul ul ul {
          list-style-type: square !important;
        }
        
        .quill-display-content blockquote {
          border-left: 4px solid #ddd;
          margin: 0.5em 0;
          padding-left: 1em;
          color: #666;
          font-style: italic;
        }
      `}</style>
    </div>
  )
}